[package]
name = "scalesocket"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
futures = "0.3.21"
id-pool = { version = "0.2.2", default-features = false, features = ["u16"] }
sender-sink = "0.1.0"
serde_json = "1.0.81"
thiserror = "1.0.31"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
tokio = { version = "1.18.2", features = ["full", "tracing"] }
tokio-stream = { version = "0.1.8", features = ["sync"] }
tokio-process-stream = "0.2.0"
warp = "0.3"
