[package]
name = "scalesocket"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
futures = "0.3.21"
serde_json = "1.0.81"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
warp = "0.3"
