version: "3"

services:
  chat:
    build:
      context: chat/
    ports:
      - "5000:5000"
    volumes:
      - ./chat/:/var/www/public
      - ./chat/:/app/

  collaborative:
    build:
      context: collaborative/
    volumes:
      - ./collaborative/:/var/www/public
      - ./collaborative/:/app/
    ports:
      - "5000:5000"

  multiplayer:
    build:
      context: multiplayer/
    volumes:
      - ./multiplayer/:/var/www/public
      - ./multiplayer/:/app/
    ports:
      - "5000:5000"

  terminal:
    build:
      context: terminal/
    volumes:
      - ./terminal/:/var/www/public
      - ./terminal/:/app/
    ports:
      - "5000:5000"
