name: ci
on:
  pull_request:
    paths:
      - "**"
      - "!README.md"
      - "!/docs/**"
      - "!/examples/**"
      - "!/LICENSE"
  push:
    branches:
      - main
    paths:
      - "**"
      - "!README.md"
      - "!/docs/**"
      - "!/examples/**"
      - "!/LICENSE"
  schedule:
    - cron: "5 5 5 * *"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: Log version
        run: |
          rustc --version
          cargo --version
          rustup --version

      - name: Build and Test
        run: cargo test --all-features --locked

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check
